# NUMPY ARRAY

In [10]:
import numpy as np


#ONE DIMENSIONAL ARRAY
first=np.array([1,2,3,4])
print(first)


print(type(first))
print(first.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [8]:
#TWO-DIMENSIONAL ARRAY
second=np.array([[1,2,3,4],[1,2,3,4]])
print(second)
print(second.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [29]:
#THREE-DIMENSIONAL ARRAY
third=np.array([[[44,55,66],[11,22,33]]])
print(third)

print(third.ndim)

[[[44 55 66]
  [11 22 33]]]
3


In [18]:
#MULTI-DIMENSIONAL ARRAY

fourth=np.array([33,44,66],ndmin=7)
print(fourth)

print(fourth.ndim)

[[[[[[[33 44 66]]]]]]]
7


In [27]:
userinput=[]
for i in range(1,5):
    uservalue=int(input('Enter Value To Insert In Array'))
    userinput.append(i)
    
fifth=np.array(userinput)
print(fifth)
print(type(fifth))


Enter Value To Insert In Array12
Enter Value To Insert In Array12
Enter Value To Insert In Array13
Enter Value To Insert In Array13
[1 2 3 4]
<class 'numpy.ndarray'>
