In [2]:
import numpy as np


# ZEROS

In [7]:
#zeros with 1d array
first=np.zeros(4)
print(first)


[0. 0. 0. 0.]


In [8]:
#zeros with 2d array
first1=np.zeros((3,4))
print(first1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#zeros with 3d array
first2=np.zeros(((3,4,3)))
print(first2)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


ONES

In [13]:
second=np.ones(4)
print(second)

[1. 1. 1. 1.]


In [15]:
#2d Array With ones
second1=np.ones((5,2))
print(second1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
#3d array with ones
second3=np.ones(((3,2,2)))
print(second3)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


# Empty Function

In [17]:
#1d empty array
third=np.empty(3)
print(third)

[0. 0. 0.]


In [20]:
#2d empty array
third1=np.empty((2,3))
print(third1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
#3d empty array
third2=np.empty((2,3,2))
print(third2)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


# Range Function

In [26]:
#1d arange Function Array -
fourth=np.arange(1,5)
print(fourth)

[1 2 3 4]


In [30]:
#2d arange Function Array
fourth1=np.arange((10))
print(fourth1)

[0 1 2 3 4 5 6 7 8 9]


# ARRAY DIAGONAL

In [33]:
fifth=np.eye((4))
print(fifth)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
