# NUMPY GENRATE RANDOM NUMBER

In [3]:
import numpy as np

#1d Array
first=np.random.rand(2)
print(first)

[0.47361892 0.589108  ]


In [5]:
#2d Array
first1=np.random.rand(4,3)
print(first1)

[[0.31104332 0.60477383 0.29374573]
 [0.65843196 0.17389071 0.70068838]
 [0.65177754 0.2714955  0.58668143]
 [0.81678143 0.88006413 0.40749522]]


In [6]:
#3d-Array
first2=np.random.rand(4,3,2)
print(first2)

[[[0.35999375 0.71217239]
  [0.87886356 0.86748153]
  [0.98857562 0.38532442]]

 [[0.51400787 0.44503408]
  [0.76967712 0.67447052]
  [0.43383924 0.93353009]]

 [[0.99515873 0.60818503]
  [0.82200761 0.8849408 ]
  [0.08337282 0.95896212]]

 [[0.11880378 0.14538881]
  [0.1743864  0.6860457 ]
  [0.99765811 0.51139   ]]]


# RANDN() FUNCTION

In [14]:
second=np.random.randn(3)
print(second)

[-1.53463024  0.41524009  0.21358595]


In [15]:
#2d Array Using randn() Function 
second1=np.random.randn(3,3)
print(second1)

[[-0.38347757  0.38099759  0.4967693 ]
 [-0.57797973  2.25226783  1.44474027]
 [ 1.58593955 -0.27942315 -0.24419016]]


# RANDINT() FUNCTION

In [16]:
third=np.random.randint(3,6,10)
print(third)

[3 3 4 5 5 3 5 3 5 3]


In [21]:
third1=np.random.randint(3,5,5)
print(third1)

[4 4 4 3 4]
