In [1]:
import numpy as np

first=np.array([10,20,30,10,5])
task=np.min(first)
print(task)

5


In [2]:
second=np.array([10,30,40,20,5])
task1=np.max(second)
print(task1)

40


In [3]:
third=np.array([30,20,10,40])
task2=np.argmin(third)
print(task2)

2


In [4]:
fourth=np.array([50,60,20,10,90])
task3=np.argmax(fourth)
print(task3)

4


In [7]:
fifth=np.array([[10,20,30],[10,20,30]])
task4=np.min(fifth,axis=1)
print(task4)

[10 10]


In [10]:
fifth=np.array([[10,2000,30],[100,200,300]])
task4=np.min(fifth,axis=0)
print(task4)

[ 10 200  30]


In [11]:
sixth=np.array([2,4,6,8])
task5=np.sqrt(sixth)
print(task5)

[1.41421356 2.         2.44948974 2.82842712]


In [12]:
seven=np.array([10,20,30,40])
task6=np.sin(seven)
print(task6)

[-0.54402111  0.91294525 -0.98803162  0.74511316]


In [14]:
eight=np.array([1,2,3,4])
task7=np.cos(seven)
print(task7)

[-0.83907153  0.40808206  0.15425145 -0.66693806]


In [15]:
nine=np.array([1,2,3,4])
task8=np.cumsum(nine)
print(task8)

[ 1  3  6 10]
