# INDEXING IN NUMPY

In [30]:
#INDEXING IN 1D ARRAY

import numpy as np
first=np.array([10,20,30,40,50])
print(first[2])
print(first[-4])
# print(first[30])                  #THIS WILL THROWS ERROR

30
20


In [34]:
#INDEXING IN 2D ARRAY
second=np.array([[10,20,30],[40,50,60]])
# print(second[1][1])
print(second[1,1])
print(second[0][2])

50
30


In [39]:
#INDEXING IN 3D ARRAY

third=np.array([[[10,20],[30,40],[50,60]]])

print(third[0,2,1])
print(third[0,1,0])

60
30


# SLICING IN NUMPY

In [43]:
#SLICING IN 1D ARRAY

fourth=np.array([1,2,3,4,5,6,7,8,9])
print(fourth[4:7])
print(fourth[:3])
print(fourth[3:])
print(fourth[::2])

[5 6 7]
[1 2 3]
[4 5 6 7 8 9]
[1 3 5 7 9]


In [45]:
#SLICING IN 2D ARRAY

fifth=np.array([[10,20,30],[40,50,60]])
print(fifth[1,1])
print(fifth[0,2])

50
30


In [49]:
#SLICING IN 3D ARRAY
sixth=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(sixth[0,2,1])
print(sixth[0,1,2])
print(sixth[0,0,0])

8
6
1
