# ARRAY JOIN IN NUMPY

In [ ]:
#JOIN FUNCTION-we can join two or more array into the single new array are known as array Join.
#              - we are use the concatenate function for join 2 array

In [4]:
#JOIN 1D ARRAY

import numpy as np
first=([10,20,30])
second=([40,50,60])

new_array=np.concatenate((first,second))
print(new_array)

[10 20 30 40 50 60]


In [9]:
#JOIN 2D ARRAY

third=([[10,20,30],[10,20,30]])
fourth=([[70,80,90],[20,30,40]])
new_result=np.concatenate((third,fourth),axis=0)
print(new_result)

[[10 20 30]
 [10 20 30]
 [70 80 90]
 [20 30 40]]


In [8]:
third=([[10,20,30],[10,20,30]])
fourth=([[70,80,90],[20,30,40]])
new_result=np.concatenate((third,fourth),axis=1)
print(new_result)

[[10 20 30 70 80 90]
 [10 20 30 20 30 40]]


In [11]:
#JOIN 3D ARRAY

fifth=([[[1,2,3],[4,5,6],[7,8,9]]])
sixth=([[[11,12,13],[14,15,16],[17,18,19]]])
new_result1=np.concatenate((fifth,sixth),axis=0)
print(new_result1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [13]:
fifth=([[[1,2,3],[4,5,6],[7,8,9]]])
sixth=([[[11,12,13],[14,15,16],[17,18,19]]])
new_result2=np.concatenate((fifth,sixth),axis=1)
print(new_result2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]
  [14 15 16]
  [17 18 19]]]
