In [1]:
import numpy as np

In [3]:
#CREATING 1D ARRAY

first=np.array([10,30,20,40,60])
print(first)
print(first.ndim)

[10 30 20 40 60]
1


In [3]:
#CREATING 2D ARRAY

import numpy as np
second=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(second)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
#CREATING 3D ARRAY-
third=np.array([[[10,20],[30,40],[50,60]]])
print(third)
print(third.ndim)

[[[10 20]
  [30 40]
  [50 60]]]
3


In [10]:
#CREATING MULTI DIMENSIONAL ARRAY-

fourth=np.array([1,2,3],ndmin=8)
print(fourth)
print(fourth.ndim)

[[[[[[[[1 2 3]]]]]]]]
8


# NUMPY FUNCTIONS

In [18]:
#1D ZEROS
fifth=np.zeros(8)
print(fifth)

print()

#2D ZEROS
fifth1=np.zeros((2,3))
print(fifth1)

print()

#3D ZEROS
fifth2=np.zeros(((6,5)))
print(fifth2)

[0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
#1D ONES

sixth=np.ones(4)
print(sixth)

print()

#2D ONES
sixth1=np.ones((3,3))
print(sixth1)

print()


#3D ONES

sixth2=np.ones(((3,4,5)))
print(sixth2)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [29]:
#1D EMPTY-
seven=np.empty(3)
print(seven)

print()

#2D EMPTY
seven1=np.empty((3,3))
print(seven1)

print()

#3D EMPTY
seven2=np.empty(((1,2,1)))
print(seven2)

[4.24399158e-313 8.48798317e-313 1.27319747e-312]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[[ 1.48027923e-221]
  [-3.52374783e-062]]]


In [45]:
#1D ARANGE-
eight=np.arange(4)
print(eight)

print()

#2D ARANGE-
eight1=np.arange(6,3)
print(eight1)

#3D ARANGE-
eight2=np.arange(9)
print(eight2)                        #GETTING ERRORS HERE

[0 1 2 3]

[]
[0 1 2 3 4 5 6 7 8]


In [51]:
#1D-EYE FUNCTION

nine=np.eye(2)
print(nine)

print()

#2D-EYE FUNCTION
nine1=np.eye(5,5)
print(nine1)

print()

#3D-EYE FUNCTION
nine2=np.eye(4,5)
print(nine2)

[[1. 0.]
 [0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# NUMPY RANDOM FUNCTION

In [60]:
#1D RANDOM-

var=np.random.rand(1)
print(var)

#2D RANDOM
var1=np.random.rand(2,2)
print(var1)

#3D RANDOM
var2=np.random.rand(3,4,5)
print(var2)

[0.23018303]
[[0.12087834 0.36974275]
 [0.76176771 0.20140313]]
[[[0.34242128 0.23507045 0.90617876 0.30393073 0.56361772]
  [0.06684502 0.20247019 0.91798022 0.93741661 0.24677963]
  [0.65460388 0.6653401  0.80422064 0.77725852 0.91189211]
  [0.14364422 0.28842234 0.71624669 0.32833784 0.81044601]]

 [[0.57001914 0.38122344 0.24455357 0.02852458 0.64979465]
  [0.67994468 0.97180135 0.47561096 0.63445907 0.80614055]
  [0.81140919 0.96498092 0.16067467 0.42946943 0.78807934]
  [0.72227063 0.86749274 0.33575533 0.54016195 0.50051474]]

 [[0.99865183 0.76625659 0.82958327 0.22541739 0.50001975]
  [0.85372706 0.08239783 0.68216589 0.89081098 0.29405977]
  [0.97866466 0.83739445 0.29588698 0.62117667 0.07415623]
  [0.84401726 0.95467223 0.5985722  0.60448018 0.29044969]]]


In [63]:
#1D RANDN-
var1=np.random.randn(1)
print(var1)

#2D RANDN-
var11=np.random.randn(2,3)
print(var11)

#3D RANDN-
var12=np.random.randn(4,2,1)
print(var12)

[-0.38832994]
[[-0.04812223  0.9147654  -0.37565805]
 [-0.23183836  0.10890744 -0.24643302]]
[[[-0.51071646]
  [-1.11602232]]

 [[-0.01680966]
  [ 0.18357954]]

 [[-0.18327256]
  [ 1.73147311]]

 [[ 0.06392515]
  [-0.79201054]]]


In [79]:
#1D RANDINT-
var2=np.random.randint(4)
print(var2)

#2D RANDINT-
var22=np.random.randint((3,5))
print(var22)

#3D RANDINT-
var23=np.random.randint(((4,5,4)))
print(var23)

1
[2 0]
[0 3 1]


# NUMPY_ARITHMATIC_OPERATIONS

In [90]:
#1D-ADDITION-
addi=np.array([10,20,30])
task1=addi+5
print(task1)

print()

#2D-ADDITION-
addi1=np.array([10,20])
addi11=np.array([50,60])
res= addi1 + addi11
print(res)

print()

#3D-ADDITION
add11=np.array([10,20])
add111=np.array([30,40])
add1111=np.array([50,60])
res1=add11+add111+add1111
print(res1)

[15 25 35]

[60 80]

[ 90 120]


In [92]:
#SUBSTRACTION
sub=np.array([40,50,60])
sub1=np.array([90,90,90])
sub_res=sub-sub1
print(sub_res)

[-50 -40 -30]


In [94]:
#MULTIPLICATION
mul=np.array([80,90,70])
mul1=np.array([1,2,3])
mul_res=mul*mul1
print(mul_res)

[ 80 180 210]


In [95]:
#DIVISION-
div=np.array([1,2,3])
div1=np.array([10,11,12])
div_res=div/div1
print(div_res)

[0.1        0.18181818 0.25      ]


# NUMPY ARITHMATIC FUNCTIONS-

In [98]:
#Min
a=np.array([10,20,30,5,60,70])
print(a.min())

5


In [99]:
#MAX-
b=np.array([1,4,3,2,8,9,33,78,99,1,3,4])
print(b.max())

99


In [100]:
#ARGMIN-it find the Minimum values Index In Array
c=np.array([10,20,30,5,60,70])
print(a.argmin())

3


In [105]:
#ARGMAX-it find the maximum values index in array-
b=np.array([1,4,3,2,8,9,33,78,99,1,3,4])
print(np.argmax(b))

8


In [104]:
#SQRT-it find the square root of an any array
findsquare=np.array([10,20,30])
print(np.sqrt(findsquare))

[3.16227766 4.47213595 5.47722558]


In [106]:
#SIN-it is used for find the Sin Value Of An array
finsin=np.array([10,20])
print(np.sin(finsin))

[-0.54402111  0.91294525]


In [107]:
#COS-it is used for find the Cos Value of An Array-
fincos=np.array([1,2,3])
print(np.cos(fincos))

[ 0.54030231 -0.41614684 -0.9899925 ]


# NUMPY INDEXING

In [112]:
#1D-INDEX
ind=np.array([10,20,30,40])
print(ind[2])
print(ind[-3])

30
20


In [115]:
#2D-INDEX
ind1=np.array([[1,2,3,4],[5,6,7,8]])
print(ind1[1,2])
print(ind1[0,-3])

7
2


In [121]:
#3D INDEX
ind2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(ind2[0,2,2])
print(ind2[0,-1,-3])

9
7


# SLICING IN NUMPY

In [124]:
#1D-SLICING
sli=np.array([1,2,3,4,5,6,7,8,9,0])
print(sli[2::])
print(sli[:5:])
print(sli[1:9:2])

[3 4 5 6 7 8 9 0]
[1 2 3 4 5]
[2 4 6 8]


In [136]:
#2D-Slicing
sli1=np.array([[10,20,30],[40,50,60]])
print(sli1[1,1])
print(sli1[0,2])

50
30


In [141]:
#3D-SLICING-
sli2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(sli2[0,2,2])
print(sli2[0,1,1])
print(sli2[0,0,0])

9
5
1


# JOIN ARRAY IN NUMPY-

In [146]:
#1D-JOIN
sli3=np.array([1,2,3])
sli4=np.array([4,5,6])
ress=np.concatenate((sli3,sli4))
print(ress)

[1 2 3 4 5 6]


In [149]:
#2D-JOIN
sli4=np.array([[1,2],[3,4]])
sli5=np.array([[5,6],[7,8]])
resss=np.concatenate((sli4,sli5),axis=1)
print(resss)

[[1 2 5 6]
 [3 4 7 8]]


In [150]:
sli4=np.array([[1,2],[3,4]])
sli5=np.array([[5,6],[7,8]])
resss=np.concatenate((sli4,sli5),axis=0)
print(resss)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
